// This file is auto-generated by @hey-api/openapi-ts

export const CitationSchema = {
  properties: {
    title: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Title',
      description: 'Title of the citation.',
    },
    url: {
      type: 'string',
      title: 'Url',
      description: 'URL of the citation.',
    },
    excerpts: {
      anyOf: [
        {
          items: {
            type: 'string',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Excerpts',
      description:
        'Excerpts from the citation supporting the output. Only certain processors provide excerpts.',
    },
  },
  type: 'object',
  required: ['url'],
  title: 'Citation',
  description: 'A citation for a task output.',
} as const

export const ErrorSchema = {
  properties: {
    ref_id: {
      type: 'string',
      title: 'Ref Id',
      description: 'Reference ID for the error.',
    },
    message: {
      type: 'string',
      title: 'Message',
      description: 'Human-readable message.',
    },
    detail: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Detail',
      description: 'Optional detail supporting the error.',
    },
  },
  type: 'object',
  required: ['ref_id', 'message'],
  title: 'Error',
  description: 'An error message.',
} as const

export const ErrorResponseSchema = {
  properties: {
    type: {
      type: 'string',
      enum: ['error'],
      const: 'error',
      title: 'Type',
      description: "Always 'error'.",
      default: 'error',
    },
    error: {
      allOf: [
        {
          $ref: '#/components/schemas/Error',
        },
      ],
      description: 'Error.',
    },
  },
  type: 'object',
  required: ['error'],
  title: 'ErrorResponse',
  description: 'Response object used for non-200 status codes.',
} as const

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const

export const JsonSchemaSchema = {
  properties: {
    json_schema: {
      type: 'object',
      title: 'Json Schema',
      description:
        'A JSON Schema object. Only a subset of JSON Schema is supported.',
      examples: [
        {
          additionalProperties: false,
          properties: {
            gdp: {
              description:
                "GDP in USD for the year, formatted like '$3.1 trillion (2023)'",
              type: 'string',
            },
          },
          required: ['gdp'],
          type: 'object',
        },
      ],
    },
    type: {
      type: 'string',
      enum: ['json'],
      const: 'json',
      title: 'Type',
      description: 'The type of schema being defined. Always `json`.',
      default: 'json',
    },
  },
  type: 'object',
  required: ['json_schema'],
  title: 'JsonSchema',
  description: 'JSON schema for a task input or output.',
} as const

export const TaskRunSchema = {
  properties: {
    run_id: {
      type: 'string',
      title: 'Run Id',
      description: 'ID of the task run.',
    },
    status: {
      type: 'string',
      enum: [
        'queued',
        'action_required',
        'running',
        'completed',
        'failed',
        'cancelling',
        'cancelled',
      ],
      title: 'Status',
      description: 'Status of the run.',
      examples: [
        'queued',
        'action_required',
        'running',
        'completed',
        'failed',
        'cancelling',
        'cancelled',
      ],
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      description:
        "Whether the run is currently active; i.e. status is one of {'running', 'queued', 'cancelling'}.",
    },
    warnings: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/shapley__search__tasks__api_v1__Warning',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Warnings',
      description: 'Warnings for the run.',
    },
    processor: {
      type: 'string',
      title: 'Processor',
      description: 'Processor used for the run.',
    },
    metadata: {
      anyOf: [
        {
          additionalProperties: {
            anyOf: [
              {
                type: 'string',
              },
              {
                type: 'integer',
              },
              {
                type: 'number',
              },
              {
                type: 'boolean',
              },
            ],
          },
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Metadata',
      description: 'User-provided metadata stored with the run.',
    },
    created_at: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Created At',
      description:
        'Timestamp of the creation of the task, as an RFC 3339 string.',
    },
    modified_at: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Modified At',
      description:
        'Timestamp of the last modification to the task, as an RFC 3339 string.',
    },
  },
  type: 'object',
  required: [
    'run_id',
    'status',
    'is_active',
    'processor',
    'created_at',
    'modified_at',
  ],
  title: 'TaskRun',
  description: 'Status of a task.',
} as const

export const TaskRunInput_InputSchema = {
  properties: {
    task_spec: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskSpec',
        },
        {
          type: 'null',
        },
      ],
      description: 'Task specification.',
    },
    input: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'object',
        },
      ],
      title: 'Input',
      description: 'Input to the task, either text or a JSON object.',
      examples: [
        'France (2023)',
        {
          country: 'France',
          year: 2023,
        },
      ],
    },
    processor: {
      type: 'string',
      title: 'Processor',
      description: 'Processor to use for the task.',
    },
    metadata: {
      anyOf: [
        {
          additionalProperties: {
            anyOf: [
              {
                type: 'string',
              },
              {
                type: 'integer',
              },
              {
                type: 'number',
              },
              {
                type: 'boolean',
              },
            ],
          },
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Metadata',
      description:
        'User-provided metadata stored with the run. Keys and values must be strings with a maximum length of 16 and 512 characters respectively.',
    },
  },
  type: 'object',
  required: ['input', 'processor'],
  title: 'TaskRunInput',
  description: 'Request to run a task.',
} as const

export const TaskRunInput_OutputSchema = {
  properties: {
    task_spec: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskSpec',
        },
        {
          type: 'null',
        },
      ],
      description: 'Task specification.',
    },
    input: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'object',
        },
      ],
      title: 'Input',
      description: 'Input to the task, either text or a JSON object.',
      examples: [
        'France (2023)',
        {
          country: 'France',
          year: 2023,
        },
      ],
    },
    processor: {
      type: 'string',
      title: 'Processor',
      description: 'Processor to use for the task.',
    },
    metadata: {
      anyOf: [
        {
          additionalProperties: {
            anyOf: [
              {
                type: 'string',
              },
              {
                type: 'integer',
              },
              {
                type: 'number',
              },
              {
                type: 'boolean',
              },
            ],
          },
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Metadata',
      description:
        'User-provided metadata stored with the run. Keys and values must be strings with a maximum length of 16 and 512 characters respectively.',
    },
  },
  type: 'object',
  required: ['input', 'processor'],
  title: 'TaskRunInput',
  description: 'Request to run a task.',
} as const

export const TaskRunJsonOutputSchema = {
  properties: {
    content: {
      type: 'object',
      title: 'Content',
      description:
        'Output from the task as a native JSON object, as determined by the output schema of the task spec.',
    },
    basis: {
      items: {
        $ref: '#/components/schemas/shapley__search__tasks__api_v1__FieldBasis',
      },
      type: 'array',
      title: 'Basis',
      description: 'Basis for each top-level field in the JSON output.',
    },
    type: {
      type: 'string',
      enum: ['json'],
      const: 'json',
      title: 'Type',
      description:
        'The type of output being returned, as determined by the output schema of the task spec.',
    },
  },
  type: 'object',
  required: ['content', 'basis', 'type'],
  title: 'TaskRunJsonOutput',
  description: 'Output from a task that returns text.',
} as const

export const TaskRunResultSchema = {
  properties: {
    run: {
      allOf: [
        {
          $ref: '#/components/schemas/TaskRun',
        },
      ],
      description: "Task run object with status 'completed'.",
    },
    output: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskRunTextOutput',
        },
        {
          $ref: '#/components/schemas/TaskRunJsonOutput',
        },
      ],
      title: 'Output',
      description: 'Output from the task conforming to the output schema.',
    },
  },
  type: 'object',
  required: ['run', 'output'],
  title: 'TaskRunResult',
  description: 'Result of a task run.',
} as const

export const TaskRunTextOutputSchema = {
  properties: {
    content: {
      type: 'string',
      title: 'Content',
      description: 'Text output from the task.',
    },
    basis: {
      items: {
        $ref: '#/components/schemas/shapley__search__tasks__api_v1__FieldBasis',
      },
      type: 'array',
      title: 'Basis',
      description:
        "Basis for the output. The basis has a single field 'output'.",
    },
    type: {
      type: 'string',
      enum: ['text'],
      const: 'text',
      title: 'Type',
      description:
        'The type of output being returned, as determined by the output schema of the task spec.',
    },
  },
  type: 'object',
  required: ['content', 'basis', 'type'],
  title: 'TaskRunTextOutput',
  description: 'Output from a task that returns text.',
} as const

export const TaskSpecSchema = {
  properties: {
    output_schema: {
      anyOf: [
        {
          $ref: '#/components/schemas/JsonSchema',
        },
        {
          $ref: '#/components/schemas/TextSchema',
        },
        {
          type: 'string',
        },
      ],
      title: 'Output Schema',
      description:
        'JSON schema or text fully describing the desired output from the task. Descriptions of output fields will determine the form and content of the response. A bare string is equivalent to a text schema with the same description.',
    },
    input_schema: {
      anyOf: [
        {
          $ref: '#/components/schemas/JsonSchema',
        },
        {
          $ref: '#/components/schemas/TextSchema',
        },
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Input Schema',
      description:
        'Optional JSON schema or text description of expected input to the task. A bare string is equivalent to a text schema with the same description.',
    },
  },
  type: 'object',
  required: ['output_schema'],
  title: 'TaskSpec',
  description: `Specification for a task.

For convenience we allow bare strings as input or output schemas, which is
equivalent to a text schema with the same description.`,
} as const

export const TextSchemaSchema = {
  properties: {
    description: {
      type: 'string',
      title: 'Description',
      description: 'A text description of the desired output from the task.',
      examples: [
        "GDP in USD for the year, formatted like '$3.1 trillion (2023)'",
      ],
    },
    type: {
      type: 'string',
      enum: ['text'],
      const: 'text',
      title: 'Type',
      description: 'The type of schema being defined. Always `text`.',
      default: 'text',
    },
  },
  type: 'object',
  required: ['description'],
  title: 'TextSchema',
  description: 'Text description for a task input or output.',
} as const

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const

export const shapley__search__tasks__api_v1__FieldBasisSchema = {
  properties: {
    field: {
      type: 'string',
      title: 'Field',
      description: 'Name of the output field.',
    },
    citations: {
      items: {
        $ref: '#/components/schemas/Citation',
      },
      type: 'array',
      title: 'Citations',
      description: 'List of citations supporting the output field.',
      default: [],
    },
    reasoning: {
      type: 'string',
      title: 'Reasoning',
      description: 'Reasoning for the output field.',
    },
    confidence: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Confidence',
      description:
        'Confidence level for the output field. Only certain processors provide confidence levels.',
      examples: ['low', 'medium', 'high'],
    },
  },
  type: 'object',
  required: ['field', 'reasoning'],
  title: 'FieldBasis',
  description: 'Citations and reasoning supporting one field of a task output.',
} as const

export const shapley__search__tasks__api_v1__WarningSchema = {
  properties: {
    type: {
      type: 'string',
      title: 'Type',
      description:
        'Type of warning. Note that adding new warning types is considered a backward-compatible change.',
      examples: ['spec_validation', 'input_validation'],
    },
    message: {
      type: 'string',
      title: 'Message',
      description: 'Human-readable message.',
    },
    detail: {
      anyOf: [
        {
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Detail',
      description: 'Optional detail supporting the warning.',
    },
  },
  type: 'object',
  required: ['type', 'message'],
  title: 'Warning',
  description: 'Human-readable message for a task.',
} as const
