// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client'
import type {
  TasksRunsPostV1TasksRunsPostData,
  TasksRunsPostV1TasksRunsPostResponses,
  TasksRunsPostV1TasksRunsPostErrors,
  TasksRunsGetV1TasksRunsRunIdGetData,
  TasksRunsGetV1TasksRunsRunIdGetResponses,
  TasksRunsGetV1TasksRunsRunIdGetErrors,
  TasksRunsInputGetV1TasksRunsRunIdInputGetData,
  TasksRunsInputGetV1TasksRunsRunIdInputGetResponses,
  TasksRunsInputGetV1TasksRunsRunIdInputGetErrors,
  TasksRunsResultGetV1TasksRunsRunIdResultGetData,
  TasksRunsResultGetV1TasksRunsRunIdResultGetResponses,
  TasksRunsResultGetV1TasksRunsRunIdResultGetErrors,
} from './types.gen'
import { client as _heyApiClient } from './client.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Tasks Runs Post
 * Initiates a single task run.
 */
export const tasksRunsPostV1TasksRunsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TasksRunsPostV1TasksRunsPostData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    TasksRunsPostV1TasksRunsPostResponses,
    TasksRunsPostV1TasksRunsPostErrors,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-api-key',
        type: 'apiKey',
      },
    ],
    url: '/v1/tasks/runs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Tasks Runs Get
 * Retrieves a run by run_id.
 */
export const tasksRunsGetV1TasksRunsRunIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TasksRunsGetV1TasksRunsRunIdGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    TasksRunsGetV1TasksRunsRunIdGetResponses,
    TasksRunsGetV1TasksRunsRunIdGetErrors,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-api-key',
        type: 'apiKey',
      },
    ],
    url: '/v1/tasks/runs/{run_id}',
    ...options,
  })
}

/**
 * Tasks Runs Input Get
 * Retrieves the input of a run by run_id.
 */
export const tasksRunsInputGetV1TasksRunsRunIdInputGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<TasksRunsInputGetV1TasksRunsRunIdInputGetData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    TasksRunsInputGetV1TasksRunsRunIdInputGetResponses,
    TasksRunsInputGetV1TasksRunsRunIdInputGetErrors,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-api-key',
        type: 'apiKey',
      },
    ],
    url: '/v1/tasks/runs/{run_id}/input',
    ...options,
  })
}

/**
 * Tasks Runs Result Get
 * Retrieves a run by run_id, blocking until the run is completed.
 */
export const tasksRunsResultGetV1TasksRunsRunIdResultGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TasksRunsResultGetV1TasksRunsRunIdResultGetData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    TasksRunsResultGetV1TasksRunsRunIdResultGetResponses,
    TasksRunsResultGetV1TasksRunsRunIdResultGetErrors,
    ThrowOnError
  >({
    security: [
      {
        name: 'x-api-key',
        type: 'apiKey',
      },
    ],
    url: '/v1/tasks/runs/{run_id}/result',
    ...options,
  })
}
