// This file is auto-generated by @hey-api/openapi-ts

/**
 * Citation
 * A citation for a task output.
 */
export type Citation = {
  /**
   * Title
   * Title of the citation.
   */
  title?: string | null
  /**
   * Url
   * URL of the citation.
   */
  url: string
  /**
   * Excerpts
   * Excerpts from the citation supporting the output. Only certain processors provide excerpts.
   */
  excerpts?: Array<string> | null
}

/**
 * Error
 * An error message.
 */
export type _Error = {
  /**
   * Ref Id
   * Reference ID for the error.
   */
  ref_id: string
  /**
   * Message
   * Human-readable message.
   */
  message: string
  /**
   * Detail
   * Optional detail supporting the error.
   */
  detail?: {
    [key: string]: unknown
  } | null
}

/**
 * ErrorResponse
 * Response object used for non-200 status codes.
 */
export type ErrorResponse = {
  /**
   * Type
   * Always 'error'.
   */
  type?: 'error'
  /**
   * Error.
   */
  error: _Error
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * JsonSchema
 * JSON schema for a task input or output.
 */
export type JsonSchema = {
  /**
   * Json Schema
   * A JSON Schema object. Only a subset of JSON Schema is supported.
   */
  json_schema: {
    [key: string]: unknown
  }
  /**
   * Type
   * The type of schema being defined. Always `json`.
   */
  type?: 'json'
}

/**
 * TaskRun
 * Status of a task.
 */
export type TaskRun = {
  /**
   * Run Id
   * ID of the task run.
   */
  run_id: string
  /**
   * Status
   * Status of the run.
   */
  status:
    | 'queued'
    | 'action_required'
    | 'running'
    | 'completed'
    | 'failed'
    | 'cancelling'
    | 'cancelled'
  /**
   * Is Active
   * Whether the run is currently active; i.e. status is one of {'running', 'queued', 'cancelling'}.
   */
  is_active: boolean
  /**
   * Warnings
   * Warnings for the run.
   */
  warnings?: Array<ShapleySearchTasksApiV1Warning> | null
  /**
   * Processor
   * Processor used for the run.
   */
  processor: string
  /**
   * Metadata
   * User-provided metadata stored with the run.
   */
  metadata?: {
    [key: string]: string | number | number | boolean
  } | null
  /**
   * Created At
   * Timestamp of the creation of the task, as an RFC 3339 string.
   */
  created_at: string | null
  /**
   * Modified At
   * Timestamp of the last modification to the task, as an RFC 3339 string.
   */
  modified_at: string | null
}

/**
 * TaskRunInput
 * Request to run a task.
 */
export type TaskRunInputInput = {
  /**
   * Task specification.
   */
  task_spec?: TaskSpec | null
  /**
   * Input
   * Input to the task, either text or a JSON object.
   */
  input:
    | string
    | {
        [key: string]: unknown
      }
  /**
   * Processor
   * Processor to use for the task.
   */
  processor: string
  /**
   * Metadata
   * User-provided metadata stored with the run. Keys and values must be strings with a maximum length of 16 and 512 characters respectively.
   */
  metadata?: {
    [key: string]: string | number | number | boolean
  } | null
}

/**
 * TaskRunInput
 * Request to run a task.
 */
export type TaskRunInputOutput = {
  /**
   * Task specification.
   */
  task_spec?: TaskSpec | null
  /**
   * Input
   * Input to the task, either text or a JSON object.
   */
  input:
    | string
    | {
        [key: string]: unknown
      }
  /**
   * Processor
   * Processor to use for the task.
   */
  processor: string
  /**
   * Metadata
   * User-provided metadata stored with the run. Keys and values must be strings with a maximum length of 16 and 512 characters respectively.
   */
  metadata?: {
    [key: string]: string | number | number | boolean
  } | null
}

/**
 * TaskRunJsonOutput
 * Output from a task that returns text.
 */
export type TaskRunJsonOutput = {
  /**
   * Content
   * Output from the task as a native JSON object, as determined by the output schema of the task spec.
   */
  content: {
    [key: string]: unknown
  }
  /**
   * Basis
   * Basis for each top-level field in the JSON output.
   */
  basis: Array<ShapleySearchTasksApiV1FieldBasis>
  /**
   * Type
   * The type of output being returned, as determined by the output schema of the task spec.
   */
  type: 'json'
}

/**
 * TaskRunResult
 * Result of a task run.
 */
export type TaskRunResult = {
  /**
   * Task run object with status 'completed'.
   */
  run: TaskRun
  /**
   * Output
   * Output from the task conforming to the output schema.
   */
  output: TaskRunTextOutput | TaskRunJsonOutput
}

/**
 * TaskRunTextOutput
 * Output from a task that returns text.
 */
export type TaskRunTextOutput = {
  /**
   * Content
   * Text output from the task.
   */
  content: string
  /**
   * Basis
   * Basis for the output. The basis has a single field 'output'.
   */
  basis: Array<ShapleySearchTasksApiV1FieldBasis>
  /**
   * Type
   * The type of output being returned, as determined by the output schema of the task spec.
   */
  type: 'text'
}

/**
 * TaskSpec
 * Specification for a task.
 *
 * For convenience we allow bare strings as input or output schemas, which is
 * equivalent to a text schema with the same description.
 */
export type TaskSpec = {
  /**
   * Output Schema
   * JSON schema or text fully describing the desired output from the task. Descriptions of output fields will determine the form and content of the response. A bare string is equivalent to a text schema with the same description.
   */
  output_schema: JsonSchema | TextSchema | string
  /**
   * Input Schema
   * Optional JSON schema or text description of expected input to the task. A bare string is equivalent to a text schema with the same description.
   */
  input_schema?: JsonSchema | TextSchema | string | null
}

/**
 * TextSchema
 * Text description for a task input or output.
 */
export type TextSchema = {
  /**
   * Description
   * A text description of the desired output from the task.
   */
  description: string
  /**
   * Type
   * The type of schema being defined. Always `text`.
   */
  type?: 'text'
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

/**
 * FieldBasis
 * Citations and reasoning supporting one field of a task output.
 */
export type ShapleySearchTasksApiV1FieldBasis = {
  /**
   * Field
   * Name of the output field.
   */
  field: string
  /**
   * Citations
   * List of citations supporting the output field.
   */
  citations?: Array<Citation>
  /**
   * Reasoning
   * Reasoning for the output field.
   */
  reasoning: string
  /**
   * Confidence
   * Confidence level for the output field. Only certain processors provide confidence levels.
   */
  confidence?: string | null
}

/**
 * Warning
 * Human-readable message for a task.
 */
export type ShapleySearchTasksApiV1Warning = {
  /**
   * Type
   * Type of warning. Note that adding new warning types is considered a backward-compatible change.
   */
  type: string
  /**
   * Message
   * Human-readable message.
   */
  message: string
  /**
   * Detail
   * Optional detail supporting the warning.
   */
  detail?: {
    [key: string]: unknown
  } | null
}

export type TasksRunsPostV1TasksRunsPostData = {
  body: TaskRunInputInput
  path?: never
  query?: never
  url: '/v1/tasks/runs'
}

export type TasksRunsPostV1TasksRunsPostErrors = {
  /**
   * Insufficient credit in account
   */
  402: ErrorResponse
  /**
   * Invalid processor in request
   */
  403: ErrorResponse
  /**
   * Request validation error
   */
  422: ErrorResponse
  /**
   * Quota temporarily exceeded
   */
  429: ErrorResponse
}

export type TasksRunsPostV1TasksRunsPostError =
  TasksRunsPostV1TasksRunsPostErrors[keyof TasksRunsPostV1TasksRunsPostErrors]

export type TasksRunsPostV1TasksRunsPostResponses = {
  /**
   * Successful Response
   */
  200: TaskRun
  /**
   * Accepted
   */
  202: TaskRun
}

export type TasksRunsPostV1TasksRunsPostResponse =
  TasksRunsPostV1TasksRunsPostResponses[keyof TasksRunsPostV1TasksRunsPostResponses]

export type TasksRunsGetV1TasksRunsRunIdGetData = {
  body?: never
  path: {
    /**
     * Run Id
     */
    run_id: string
  }
  query?: never
  url: '/v1/tasks/runs/{run_id}'
}

export type TasksRunsGetV1TasksRunsRunIdGetErrors = {
  /**
   * Run not found
   */
  404: ErrorResponse
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TasksRunsGetV1TasksRunsRunIdGetError =
  TasksRunsGetV1TasksRunsRunIdGetErrors[keyof TasksRunsGetV1TasksRunsRunIdGetErrors]

export type TasksRunsGetV1TasksRunsRunIdGetResponses = {
  /**
   * Successful Response
   */
  200: TaskRun
}

export type TasksRunsGetV1TasksRunsRunIdGetResponse =
  TasksRunsGetV1TasksRunsRunIdGetResponses[keyof TasksRunsGetV1TasksRunsRunIdGetResponses]

export type TasksRunsInputGetV1TasksRunsRunIdInputGetData = {
  body?: never
  path: {
    /**
     * Run Id
     */
    run_id: string
  }
  query?: never
  url: '/v1/tasks/runs/{run_id}/input'
}

export type TasksRunsInputGetV1TasksRunsRunIdInputGetErrors = {
  /**
   * Not Found
   */
  404: ErrorResponse
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TasksRunsInputGetV1TasksRunsRunIdInputGetError =
  TasksRunsInputGetV1TasksRunsRunIdInputGetErrors[keyof TasksRunsInputGetV1TasksRunsRunIdInputGetErrors]

export type TasksRunsInputGetV1TasksRunsRunIdInputGetResponses = {
  /**
   * Successful Response
   */
  200: TaskRunInputOutput
}

export type TasksRunsInputGetV1TasksRunsRunIdInputGetResponse =
  TasksRunsInputGetV1TasksRunsRunIdInputGetResponses[keyof TasksRunsInputGetV1TasksRunsRunIdInputGetResponses]

export type TasksRunsResultGetV1TasksRunsRunIdResultGetData = {
  body?: never
  path: {
    /**
     * Run Id
     */
    run_id: string
  }
  query?: {
    /**
     * Timeout
     */
    timeout?: number
  }
  url: '/v1/tasks/runs/{run_id}/result'
}

export type TasksRunsResultGetV1TasksRunsRunIdResultGetErrors = {
  /**
   * Run failed or run id not found
   */
  404: ErrorResponse
  /**
   * Run still active
   */
  408: ErrorResponse
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TasksRunsResultGetV1TasksRunsRunIdResultGetError =
  TasksRunsResultGetV1TasksRunsRunIdResultGetErrors[keyof TasksRunsResultGetV1TasksRunsRunIdResultGetErrors]

export type TasksRunsResultGetV1TasksRunsRunIdResultGetResponses = {
  /**
   * Successful Response
   */
  200: TaskRunResult
}

export type TasksRunsResultGetV1TasksRunsRunIdResultGetResponse =
  TasksRunsResultGetV1TasksRunsRunIdResultGetResponses[keyof TasksRunsResultGetV1TasksRunsRunIdResultGetResponses]

export type ClientOptions = {
  baseUrl: 'https://api.parallel.ai' | (string & {})
}
